### ISSUE TITLE
Uncaught SecurityError

### ISSUE THREAD

**Issue by berhalak** [jperon/kanban#1]
Hi @jperon 

I have this error when running this widget? Is this caused by the old version of the sandobox?

```
Uncaught SecurityError: Failed to read a named property '__eq__' from 'Window': Blocked a frame with origin "http://localhost:8888" from accessing a cross-origin frame.
    at ρσ_equals (eval at module.exports (eval at load (http://localhost:8888/js/rapydscript.js:200:12)), <anonymous>:634:23)
    at listener (eval at window.onload (http://localhost:8888/js/load-pyj.js:11:7), <anonymous>:222:75)
 ```

And one more question. Is it possible to configure the widget in such a way that it is in "installed" state from the start. I tried setting `installed` option inside `[widget]` section, but I don't think that will work.

**Comment by jperon** [comment]
This should be fixed by the last (force-pushed, sorry!) update.
